<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Data\cards.catalog.json" />
    <Content Remove="Data\users.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FeastOfTheNarts.Core\FeastOfTheNarts.Core.csproj" />
    <ProjectReference Include="..\FeastOfTheNarts.Infrastructure\FeastOfTheNarts.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\lib\" />
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Data\cards.catalog.json" />
    <None Include="Data\users.json" />
  </ItemGroup>

</Project>
